openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /users:
    get:
      tags:
        - chatterbook-controller
      operationId: getUserList
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /users/{username}:
    get:
      tags:
        - chatterbook-controller
      operationId: getUserByUsername
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /users/{username}/posts:
    get:
      tags:
        - chatterbook-controller
      operationId: getPostsByUsername
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
